name: Setup Python Environment with uv
description: Sets up Python, installs uv, and creates the virtual environment.
inputs:
  only-dev:
    description: Whether to install only dev dependencies
    required: false
    default: 'false'

runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@v5
    with:
      enable-cache: true

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version-file: pyproject.toml

  - name: Install LSL and display dependencies on Ubuntu
    if: runner.os == 'Linux'
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y build-essential cmake xvfb \
        libegl1-mesa-dev libgl1-mesa-glx libxkbcommon-x11-0 \
        libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
        libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 \
        libxcb-xfixes0 libxcb-shape0 libglib2.0-0 \
        libxcb-cursor0 libxcb-util1 libegl1-mesa \
        libgles2-mesa-dev libglu1-mesa-dev \
        qt6-base-dev qt6-tools-dev qt6-tools-dev-tools
      git clone --depth=1 https://github.com/sccn/liblsl.git
      cd liblsl
      mkdir build && cd build
      cmake ..
      make -j
      sudo make install
      sudo ldconfig
      cd ../..
      rm -rf liblsl
      # Set display for headless GUI testing
      export DISPLAY=:99.0

  - name: Install dependencies
    if: steps.cache-venv.outputs.cache-hit != 'true'
    shell: bash
    run: |-
      if [[ "${{ inputs.only-dev }}" == "true" ]]; then
        uv sync --only-dev
      else
        uv sync
      fi
