name: Python Tests

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup venv
        uses: ./.github/actions/setup-venv
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=:99.0
      - name: Run tests
        id: run-tests
        env:
          DISPLAY: :99.0
        run: >
          uv run pytest \
            --junitxml=pytest.xml \
            --cov-report=term-missing:skip-covered \
            --cov-report=xml:coverage.xml \
            --cov=src tests \
            --log-level=DEBUG \
            --verbose
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
      with:
        only-dev: true
    - name: Ruff format
      run: uv run ruff format --check
    - name: Ruff check
      run: uv run ruff check

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
    - run: |
        uv run mypy .

  deptry:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup venv
      uses: ./.github/actions/setup-venv
    - run: |-
        uv run deptry ./src
